const fs = require("fs");
const path = require("path");
const https = require("https");
const categories = {
  "ISLAMIC-VIDEO": [
      "https://i.imgur.com/3EXzdzu.mp4",
      "https://i.imgur.com/elsJxEk.mp4",
      "https://i.imgur.com/htitv6P.mp4",
      "https://i.imgur.com/iD8lpOs.mp4",
      "https://i.imgur.com/PjTN0I5.mp4",
      "https://i.imgur.com/hzFQ4Xu.mp4",
      "https://i.imgur.com/8WojIf7.mp4",
      "https://i.imgur.com/guefl5P.mp4",
      "https://i.imgur.com/7zFKSsJ.mp4",
      "https://i.imgur.com/5Vys7Eb.mp4",
      "https://i.imgur.com/B6fu243.mp4",
      "https://i.imgur.com/53dHYJM.mp4",
      "https://i.imgur.com/pCWDq0c.mp4",
      "https://i.imgur.com/bytY1SY.mp4",
      "https://i.imgur.com/oWZkJ7b.mp4",
      "https://i.imgur.com/P8aujG8.mp4",
      "https://i.imgur.com/g0Fj7Ch.mp4",
      "https://i.imgur.com/nE1Z3kz.mp4",
      "https://i.imgur.com/AxnZq05.mp4",
      "https://i.imgur.com/sXYLgUB.mp4",
      "https://i.imgur.com/JjFKInj.mp4",
      "https://i.imgur.com/2OqRU40.mp4",
      "https://i.imgur.com/uRQGaK6.mp4",
      "https://i.imgur.com/3Hp0Oxy.mp4",
      "https://i.imgur.com/0Sqtett.mp4",
      "https://i.imgur.com/uZI7DXV.mp4",
      "https://i.imgur.com/soL5Jxy.mp4",
      "https://i.imgur.com/Rr2tG0T.mp4",
      "https://i.imgur.com/cNJ5j47.mp4",
      "https://i.imgur.com/OVwJaDx.mp4",
      "https://i.imgur.com/EXGhWrC.mp4",
      "https://i.imgur.com/2JvDA4e.mp4",
      "https://i.imgur.com/ZWVwq1l.mp4",
      "https://i.imgur.com/FpuexGp.mp4",
      "https://i.imgur.com/Ew7CvTt.mp4",
      "https://i.imgur.com/V0OqX8g.mp4",
      "https://i.imgur.com/JmUDnqb.mp4",
      "https://i.imgur.com/FUnr5qQ.mp4",
      "https://i.imgur.com/AQwbIOr.mp4",
      "https://i.imgur.com/Tmt0IGj.mp4",
      "https://i.imgur.com/v0I3a1W.mp4",
      "https://i.imgur.com/Ai6RzC5.mp4",
      "https://i.imgur.com/cLbms2h.mp4",
      "https://i.imgur.com/WVitFo7.mp4",
      "https://i.imgur.com/tl5pUKV.mp4",
      "https://i.imgur.com/MqwgGtt.mp4",
      "https://i.imgur.com/xeZsWGT.mp4",
      "https://i.imgur.com/ggaGB0v.mp4",
      "https://i.imgur.com/qTSRbNF.mp4",
      "https://i.imgur.com/d8GRdba.mp4",
      "https://i.imgur.com/6J5V9qA.mp4",
      "https://i.imgur.com/W2tlljJ.mp4",
      "https://i.imgur.com/Bma5E6H.mp4",
      "https://i.imgur.com/zJO00lU.mp4",
      "https://i.imgur.com/iK7HgGJ.mp4",
      "https://i.imgur.com/AGgrxCv.mp4",
      "https://i.imgur.com/fxYQOh3.mp4",
      "https://i.imgur.com/lMtE97b.mp4",
      "https://i.imgur.com/W7Sl7Lg.mp4",
      "https://i.imgur.com/wVkIgip.mp4",
      "https://i.imgur.com/rKPBWbh.mp4",
      "https://i.imgur.com/JaZUUm9.mp4",
      "https://i.imgur.com/IlxXBo3.mp4",
      "https://i.imgur.com/ho6L4po.mp4",
      "https://i.imgur.com/AxqytnF.mp4",
      "https://drive.google.com/uc?id=1607fc8LKeiwjPNIvdY448d5H2_yeQGSy",
      "https://drive.google.com/uc?id=14emH_6vF3fuJe2vmeC52e575TppboHne",
      "https://drive.google.com/uc?id=15APJbSuGLY7zCiZsAgU7HjCJeinYDX9K",
      "https://drive.google.com/uc?id=15ImMIXM_mqPM8hXpQNPLTGCrm9sh0RPS",
      "https://drive.google.com/uc?id=14qUnMm3J3cUqImDDy4ehRjDiv_NeRpMo",
      "https://drive.google.com/uc?id=15ZqanDuEYrC-lHSsiIYAjWagr1h8yZpP",
      "https://drive.google.com/uc?id=155rlKywUHP3xzgJkQ1ztxXpKnDxXtXlb",
      "https://drive.google.com/uc?id=156MaTKck-_ureBfj7NI-iU7_rGut-ssD",
      "https://drive.google.com/uc?id=15l4gxljfoe9-WvQKzffjambLC5Tt1YNd",
      "https://drive.google.com/uc?id=15fauLjjElJ0loxajhUvDeaKTqW4YdskK",
      "https://drive.google.com/uc?id=16IBAHr7AlKM1RR4hiTBuvAn5x27ed6j4",
      "https://drive.google.com/uc?id=15amvNN6WLIKwg17ufgFhs7EqI0EXNxy5",
      "https://drive.google.com/uc?id=15OS5gFi2QGZm5TTStIn6iD3YRUNHw1Zm",
      "https://drive.google.com/uc?id=168qMjWaEyObyBgJrilyTb4vOcvgynQAD",
      "https://drive.google.com/uc?id=15FFHINVpAbr4ykjkhk1_vQ5uDQakTcpy",
      "https://drive.google.com/uc?id=14j501R3TheTH3YLInLZlLTU-oXVvjegw",
      "https://drive.google.com/uc?id=15UmCBW1ddt6Kpt9xytqPpXiJip-05bDG",
      "https://drive.google.com/uc?id=14e0lCDG6vwzGi8apiDcm38Wov911501y",
      "https://drive.google.com/uc?id=15Cbl-YGajKcV0QMp6bDtRT4dI-K6lWR0",
      "https://drive.google.com/uc?id=15hJ9St2amhdLnowAvuDn0BicgZ5Aw0rW",
      "https://drive.google.com/uc?id=15QIjrXblGNjf5b3J6dRQ4XMSV-_j7soB",
      "https://drive.google.com/uc?id=15tgfSnX-ICfO8V5T6vXbb_AwYkfl_EYX",
  ],
  "COUPLE-VIDEO": [
      "https://i.imgur.com/UtKEhr0.mp4",
      "https://i.imgur.com/iIaWTaC.mp4",
      "https://i.imgur.com/l1qlgvS.mp4",
      "https://i.imgur.com/7f3zzP1.mp4",
      "https://i.imgur.com/cAnQykl.mp4",
      "https://i.imgur.com/93yveNx.mp4",
      "https://i.imgur.com/S1hPcWP.mp4",
      "https://i.imgur.com/GcyMXs6.mp4",
      "https://i.imgur.com/4GSI2i8.mp4",
      "https://i.imgur.com/7jMAqqR.mp4",
      "https://i.imgur.com/3DjfALk.mp4",
      "https://i.imgur.com/99UQY5i.mp4",
      "https://i.imgur.com/w2hX8p9.mp4",
      "https://i.imgur.com/u6w2wCw.mp4",
      "https://i.imgur.com/qbHb4TV.mp4",
      "https://i.imgur.com/oVOPILK.mp4",
      "https://i.imgur.com/XYIixNU.mp4",
      "https://i.imgur.com/V3TqiXF.mp4",
      "https://i.imgur.com/3hx98bS.mp4",
      "https://i.imgur.com/hdx7x0j.mp4",
      "https://i.imgur.com/ofB5UPz.mp4",
      "https://i.imgur.com/pljQEPg.mp4",
      "https://i.imgur.com/SE3DgRT.mp4",
      "https://i.imgur.com/a9yHovY.mp4",
      "https://i.imgur.com/0ldaQFb.mp4",
      "https://i.imgur.com/cfcMXOi.mp4",
      "https://i.imgur.com/OwzP64Y.mp4",
      "https://i.imgur.com/65dBzTD.mp4",
      "https://i.imgur.com/Q5z7xZt.mp4",
      "https://i.imgur.com/rBvRkAq.mp4",
      "https://i.imgur.com/dE2aFPX.mp4",
      "https://i.imgur.com/B5myZLc.mp4",
      "https://i.imgur.com/d7al0kz.mp4",
      "https://i.imgur.com/wGO7lxC.mp4",
      "https://i.imgur.com/XYsmu14.mp4",
      "https://i.imgur.com/RVsTiRm.mp4",
      "https://i.imgur.com/0ukh2CK.mp4",
      "https://i.imgur.com/sEtUDg2.mp4",
      "https://i.imgur.com/e9B6Xqx.mp4",
      "https://i.imgur.com/W5dKfLc.mp4",
      "https://i.imgur.com/vSMFyaD.mp4",
      "https://i.imgur.com/ZJsfgkG.mp4",
      "https://i.imgur.com/P1QJVHY.mp4",
      "https://i.imgur.com/x7LYsp7.mp4",
      "https://i.imgur.com/KRdDVBp.mp4",
      "https://i.imgur.com/HBaXulv.mp4",
      "https://i.imgur.com/iA0wpCd.mp4",
      "https://i.imgur.com/gfgxieW.mp4",
        "https://i.imgur.com/43aO3Nn.mp4",
        "https://i.imgur.com/1ZTM6DT.mp4",
        "https://i.imgur.com/yTmA5HF.mp4",
        "https://i.imgur.com/6P9GLyH.mp4",
        "https://i.imgur.com/qUQMqBO.mp4",
        "https://i.imgur.com/6B5GyxD.mp4",
        "https://i.imgur.com/r99fNFk.mp4",
        "https://i.imgur.com/ddFVO87.mp4",
        "https://i.imgur.com/u8L9HGF.mp4",
        "https://i.imgur.com/zcibYK7.mp4",
        "https://i.imgur.com/Ikadz0Z.mp4",
        "https://i.imgur.com/RXanGhO.mp4",
        "https://i.imgur.com/LtBd5zy.mp4",
        "https://i.imgur.com/CvFKWhc.mp4",
        "https://i.imgur.com/pOn0wcX.mp4",
        "https://i.imgur.com/4x07AvR.mp4",
        "https://i.imgur.com/Rf8wj3R.mp4",
        "https://i.imgur.com/7THpS7L.mp4",
        "https://i.imgur.com/Y323uee.mp4",
        "https://i.imgur.com/yeFqV9d.mp4",
        "https://i.imgur.com/mJoVzEg.mp4",
        "https://i.imgur.com/WlPTRzv.mp4",
        "https://i.imgur.com/XVbr337.mp4",
        "https://i.imgur.com/QygK30k.mp4",
        "https://i.imgur.com/V6EOaiO.mp4",
        "https://i.imgur.com/mCFNiXt.mp4",
        "https://i.imgur.com/S8I7fH4.mp4",
        "https://i.imgur.com/0Yu5y5l.mp4",
        "https://i.imgur.com/O9GP9iZ.mp4",
        "https://i.imgur.com/KGA0RBA.mp4",
        "https://i.imgur.com/mdHHxzX.mp4",
        "https://i.imgur.com/DMU6eTu.mp4",
        "https://i.imgur.com/boWuxIu.mp4",
        "https://i.imgur.com/aHua4Dh.mp4",
        "https://i.imgur.com/oQ03oPf.mp4",
        "https://i.imgur.com/WSCcoQT.mp4",
        "https://i.imgur.com/r7E2Xmv.mp4",
        "https://i.imgur.com/o495Tr6.mp4",
        "https://i.imgur.com/I4SnGpF.mp4",
        "https://i.imgur.com/tGn5AXl.mp4",
        "https://i.imgur.com/3FgCnEm.mp4",
        "https://i.imgur.com/taEqWUk.mp4",
        "https://i.imgur.com/altj0gz.mp4",
        "https://i.imgur.com/8pKd0x2.mp4",
        "https://i.imgur.com/qoeSExU.mp4",
        "https://i.imgur.com/x7LYsp7.mp4",
        "https://i.imgur.com/KRdDVBp.mp4",
        "https://i.imgur.com/STNajBB.mp4",
        "https://i.imgur.com/HBaXulv.mp4",
        "https://i.imgur.com/iA0wpCd.mp4",
        "https://i.imgur.com/J7qPrpr.mp4",
        "https://i.imgur.com/b5TbJc8.mp4",
        "https://i.imgur.com/Ok2BR3t.mp4",
        "https://i.imgur.com/rpSDliz.mp4",
        "https://i.imgur.com/ey8NJy2.mp4",
        "https://i.imgur.com/qEXaIVT.mp4",
        "https://i.imgur.com/i2Jj4KS.mp4",
        "https://i.imgur.com/u5EvR8G.mp4",
        "https://i.imgur.com/YC64kD4.mp4",
        "https://i.imgur.com/1XY7gEm.mp4",
        "https://i.imgur.com/Tv1DMT4.mp4",
        "https://i.imgur.com/rfS4ihW.mp4",
        "https://i.imgur.com/fYl4DRh.mp4",
        "https://i.imgur.com/WxDW5wX.mp4",
        "https://i.imgur.com/zXjPa6A.mp4",
        "https://i.imgur.com/KtbfcKD.mp4",
        "https://i.imgur.com/lkuN5U0.mp4",
        "https://i.imgur.com/Wv85YgQ.mp4",
        "https://i.imgur.com/GVE1Nbm.mp4",
        "https://i.imgur.com/TobpCyu.mp4",
        "https://i.imgur.com/97vEPqO.mp4",
        "https://i.imgur.com/EmD9iPX.mp4",
        "https://i.imgur.com/FpKdJk9.mp4",
        "https://i.imgur.com/u47ToWR.mp4",
        "https://i.imgur.com/6xIVvJd.mp4",
        "https://i.imgur.com/xqms4ja.mp4",
        "https://i.imgur.com/EqUlV7n.mp4",
        "https://i.imgur.com/6WA09Vh.mp4",
        "https://i.imgur.com/BBDW3Rq.mp4",
        "https://i.imgur.com/P2VN5vA.mp4",
        "https://i.imgur.com/J25ZSn2.mp4",
        "https://i.imgur.com/KELcIRX.mp4",
        "https://i.imgur.com/J25ZSn2.mp4",
        "https://i.imgur.com/KELcIRX.mp4",
        "https://i.imgur.com/BfksKgK.mp4",
        "https://i.imgur.com/YLdLfm2.mp4",
        "https://i.imgur.com/nWCXEKq.mp4",
        "https://i.imgur.com/84OA0Bj.mp4",
        "https://i.imgur.com/3wYEwbI.mp4",
        "https://i.imgur.com/ZUxKmxe.mp4",
        "https://i.imgur.com/P1nAqzZ.mp4",
        "https://i.imgur.com/GrtTCT2.mp4",
        "https://i.imgur.com/pG2A3oc.mp4",
        "https://i.imgur.com/ASDe8rb.mp4",
        "https://i.imgur.com/0czk2iY.mp4",
        "https://i.imgur.com/lgbo3Vl.mp4",
        "https://i.imgur.com/KhXcUy3.mp4",
        "https://i.imgur.com/W071YUz.mp4",
        "https://i.imgur.com/sNujqcx.mp4",
        "https://i.imgur.com/zmbIS1H.mp4",
        "https://i.imgur.com/vhMJqsx.mp4",
        "https://i.imgur.com/BufXEgS.mp4",
        "https://i.imgur.com/ClBRcZv.mp4",
        "https://i.imgur.com/EEKg4kP.mp4",
        "https://i.imgur.com/7pehprM.mp4",
        "https://i.imgur.com/8Kz0rkn.mp4",
        "https://i.imgur.com/fGNIkj3.mp4",
        "https://i.imgur.com/KugHCGl.mp4",
        "https://i.imgur.com/W8SsPgI.mp4",
        "https://i.imgur.com/QjfFppJ.mp4"
  ],
  "LOVE-VIDEO": [
      "https://drive.google.com/uc?id=1Z-6qll7ACq8Ka1pKpnC3guGcXU0gNvoL",
      "https://drive.google.com/uc?id=1YHm_oC7xItLokbt_MCWu-VdMGavvx-G4",
      "https://drive.google.com/uc?id=1YvDanPpMZKK4s547h9Bsf0uL719AvVEG",
      "https://drive.google.com/uc?id=1YemK-RQH3gUX_I9ThgNJLC89yPF-VtEY",
      "https://drive.google.com/uc?id=1YN25UGQQCpZvN29Y5a84ZCYlL-rc_JL_",
      "https://drive.google.com/uc?id=1YXbox7CyKc6Gu-56WAtAPlxSTs51Yo9n",
      "https://drive.google.com/uc?id=1YNVe1cEM0JM3lj7sU49tuJn4-8ASYVd8",
      "https://drive.google.com/uc?id=1ZDjeuPfIyUkovgmJCRsE7vE67aOe0Sp2",
      "https://drive.google.com/uc?id=1YcJciCtidcUxRGihUyx2uDgDg3cBYUE5",
      "https://drive.google.com/uc?id=1ZIE6xPwXg6_oxG0K7xCWKS04MNyag3QL",
      "https://drive.google.com/uc?id=1ZF9cOD_fj26rpWDf6WOjUQNz8QuRJhkv",
      "https://drive.google.com/uc?id=1ZAXQwA5BsnN555FrWii2bb-kdLaoMxLP",
      "https://drive.google.com/uc?id=1YvWRk-wQ_I8kuJzOuw2Mx7Q-Rrgbw6CT",
      "https://drive.google.com/uc?id=1Z8vKgEBUkKbwgMPvv_6K_lvVsrBca_X8",
      "https://drive.google.com/uc?id=1ZG-BJq7pP4oh93U6tHIKuYvZ8XiidlCV",
  ],
  "STATUS-VIDEO": [
      "https://drive.google.com/uc?id=1EIb4-oLJ_rYorvSnrdkUcBvSpx1Npi6R",
      "https://drive.google.com/uc?id=1E9kEJQqsbG0wCPeFSv0BoVbEomRQMpqn",
      "https://drive.google.com/uc?id=1E0INIbfWBO6flhfsZt3KeFfhPIYsy3Eg",
      "https://drive.google.com/uc?id=1E03OPSypd0rJFKSWr_JY8Z_6psryqjlz",
      "https://drive.google.com/uc?id=1Dt6IBBoaxpUYuXTA6QM3Nm4MJ__lOVIE",
      "https://drive.google.com/uc?id=1DflI5mf-irqYkvqN5Gx86CvXJqU6Os78",
      "https://drive.google.com/uc?id=1DenhEeDNqXwxRTXJWFwjmt3xsXZfzWVn",
      "https://drive.google.com/uc?id=1EKhW8Z2MuWmM2crIYTVer3XEBc0AZWz3",
      "https://drive.google.com/uc?id=1EUIMopqHE8jK5mTH7x4ZWG7BlmVGo9T5",
      "https://drive.google.com/uc?id=1ESEea8QJhsJbck99uh6yR6c6DIK2-9nE",
      "https://drive.google.com/uc?id=1EJiyiD7Ss6YVzdW25iKyDrDgCm80YEFE",
      "https://drive.google.com/uc?id=1E5BYhcFPSmgGuuSrwlpymtRniafE0dnL",
      "https://drive.google.com/uc?id=1E1DVUGbVZJG7fFFZkkvSVpJrNYU9sP0F",
      "https://drive.google.com/uc?id=1Dou9vhbzKnJP4YOW8Hy_yvXPNQVWF0hp"
],
"SAD-VIDEO": [
      "https://i.imgur.com/gxEZBV3.mp4",
      "https://i.imgur.com/922SK6n.mp4",
      "https://i.imgur.com/hup72M7.mp4",
      "https://i.imgur.com/i4LFfcu.mp4",
      "https://i.imgur.com/GcvzaXx.mp4",
      "https://i.imgur.com/Oi0Pvuu.mp4",
      "https://i.imgur.com/vqD0c2q.mp4",
      "https://i.imgur.com/7ORsoKf.mp4",
      "https://i.imgur.com/qYQEAIB.mp4",
      "https://i.imgur.com/BOmHsyH.mp4",
      "https://i.imgur.com/ppN0ZyP.mp4",
      "https://i.imgur.com/UcjQY4L.mp4",
      "https://i.imgur.com/HPAGz1p.mp4",
      "https://i.imgur.com/1PViCD0.mp4",
      "https://i.imgur.com/qbNAfXm.mp4",
      "https://i.imgur.com/YcA3vSG.mp4",
      "https://i.imgur.com/s8Phnz8.mp4",
      "https://i.imgur.com/M8FtvL4.mp4",
      "https://i.imgur.com/dnH1hkP.mp4",
      "https://i.imgur.com/LhnNOpd.mp4",
      "https://i.imgur.com/X5EbxXx.mp4",
      "https://i.imgur.com/wfoKOGm.mp4",
      "https://i.imgur.com/KsN9rjh.mp4",
      "https://i.imgur.com/ixARUtV.mp4",
      "https://i.imgur.com/ICMr18L.mp4",
      "https://i.imgur.com/MhhgRNT.mp4",
      "https://i.imgur.com/zXfgXcW.mp4",
      "https://i.imgur.com/inFjSXQ.mp4",
      "https://i.imgur.com/ixarKZq.mp4",
      "https://i.imgur.com/Udc9BxT.mp4",
      "https://i.imgur.com/IRATz3B.mp4",
      "https://i.imgur.com/KNgLMEf.mp4",
      "https://i.imgur.com/mzgDu8F.mp4",
      "https://i.imgur.com/gind8qB.mp4",
      "https://i.imgur.com/tEUE391.mp4",
      "https://i.imgur.com/XnPZJKo.mp4",
      "https://i.imgur.com/e3eqdmI.mp4",
      "https://i.imgur.com/SaFLAzV.mp4",
      "https://i.imgur.com/Sj5rRTY.mp4",
      "https://i.imgur.com/y0MCCn1.mp4",
      "https://i.imgur.com/diuVaqL.mp4",
      "https://i.imgur.com/oYOCqyU.mp4",
      "https://i.imgur.com/0ztfMSa.mp4",
      "https://i.imgur.com/wF5QPb6.mp4",
      "https://i.imgur.com/PymRza6.mp4",
      "https://i.imgur.com/wFdCSib.mp4",
      "https://i.imgur.com/JCH1Agc.mp4",
      "https://i.imgur.com/AEhvxyV.mp4",
      "https://i.imgur.com/E0tWA3v.mp4",
      "https://i.imgur.com/7a8UUkO.mp4",
      "https://i.imgur.com/4mFVYK8.mp4",
      "https://i.imgur.com/nN6Ifhw.mp4",
      "https://i.imgur.com/DgqSVjy.mp4",
      "https://i.imgur.com/HgiaYjr.mp4",
      "https://drive.google.com/uc?id=16KeE4J7L2Pd8cCKIBvlwEPP07A92b-eb",
      "https://drive.google.com/uc?id=16MhNPi_H0-tEe5PQrrqkx_l7SrC_l0kd",
      "https://drive.google.com/uc?id=15w4cvYmKrCW2Hul2AcvPEk5S4b-CH3EE",
      "https://drive.google.com/uc?id=16Xa6thSHdEGCiypaetbAEqVCwEAzFnKX",
      "https://drive.google.com/uc?id=16BnRPvKQd7gd3YLR_rB9QNZymotMqHu7",
      "https://drive.google.com/uc?id=15fDe2735O50z-3G4yQ5tDT9J873x5izm",
      "https://drive.google.com/uc?id=16HgiGU7_Cdh8NtpsKi92dTJmALJCV8jD",
      "https://drive.google.com/uc?id=16KTSrInqvioGnT7RrAskjHYqz8R6RgNY",
      "https://drive.google.com/uc?id=162yWrNRRTeN4tFEjQEtsR4p-4gWbTFaS",
      "https://drive.google.com/uc?id=16-q768c6nXstZEjQhWa1pZUPL2Xpjwo9",
      "https://drive.google.com/uc?id=15bfkP01mTzXutgP_0Z1iyud7SXqq-jOt",
      "https://drive.google.com/uc?id=15WnvdFOQIhKQ1nlZgsABXaf6Q2nQexGW",
      "https://drive.google.com/uc?id=16GTgYVSIDduUs4VTxadIzPPyp9KA_102",
      "https://drive.google.com/uc?id=15Y2GnA-Kcox8Mw6jioxHc1G1yP4pihnC",
      "https://drive.google.com/uc?id=16-qsG6oldtJiGq11Q3bFxKzuZJRFnoPT",
      "https://drive.google.com/uc?id=15W8ETDBXrn_JvealPwPFQ2CjvZp437-g",
      "https://drive.google.com/uc?id=15StZMKfsTdAhhECdKjS6FUFwG_OIHa7W",
      "https://drive.google.com/uc?id=16lOXxs-Z9u-mxttFnwWzdUHvrP55aHnZ",
      "https://drive.google.com/uc?id=162Qn-pcnc9iijg5dv59S9DTTQOofL4Fy",
      "https://drive.google.com/uc?id=1680rf1wQ2TrRuSLHtTwFC7GYctJAnHaX",
      "https://drive.google.com/uc?id=16-XtMXpa4r1iFJTBS2N68ARMuDH2IWpG",
      "https://drive.google.com/uc?id=15bO3lguAxsMZPvKkcvlsM6ObXOfJMz79"
],
"ANIME-VIDEO": [
      "https://i.imgur.com/uykTmIq.mp4",
      "https://i.imgur.com/OKv9G8S.mp4",
      "https://i.imgur.com/JFB2EDm.mp4",
      "https://i.imgur.com/AZ2yc7K.mp4",
      "https://i.imgur.com/Vph1L6w.mp4",
      "https://i.imgur.com/GJVqdS7.mp4",
      "https://i.imgur.com/oHJCpVW.mp4",
      "https://i.imgur.com/7U3piUc.mp4",
      "https://i.imgur.com/lDDBFYH.mp4",
      "https://i.imgur.com/OKv9G8S.mp4",
            "https://i.imgur.com/EmgFapW.mp4",
      "https://i.imgur.com/0Zq5fIL.mp4",
      "https://i.imgur.com/i8M9YeG.mp4",
      "https://i.imgur.com/9k4f3cw.mp4",
      "https://i.imgur.com/02bMIwx.mp4",
      "https://i.imgur.com/cEX9Shv.mp4",
      "https://i.imgur.com/9fb8kyN.mp4",
      "https://i.imgur.com/Jmqzdzj.mp4",
      "https://i.imgur.com/EmgFapW.mp4",
      "https://i.imgur.com/i8M9YeG.mp4",
      "https://i.imgur.com/cEX9Shv.mp4",
      "https://i.imgur.com/lLTTRgx.mp4",
      "https://i.imgur.com/mNGFGWd.mp4",
      "https://i.imgur.com/Av0I6kd.mp4",
      "https://i.imgur.com/IT68gkr.mp4",
      "https://i.imgur.com/QNsVlAz.mp4",
      "https://i.imgur.com/mdyhVSR.mp4",
      "https://i.imgur.com/D2rSL80.mp4",
      "https://i.imgur.com/JjI5x0o.mp4",
      "https://i.imgur.com/siRLWDm.mp4",
      "https://i.imgur.com/2vxb7qq.mp4",
      "https://i.imgur.com/zFfqqFh.mp4",
      "https://i.imgur.com/PSF642A.mp4",
      "https://i.imgur.com/TWw2O8K.mp4",
      "https://i.imgur.com/wscK2NB.mp4",
      "https://i.imgur.com/dU00I8t.mp4",
      "https://i.imgur.com/mw2KglD.mp4",
      "https://i.imgur.com/lLTTRgx.mp4",
      "https://i.imgur.com/mNGFGWd.mp4",
      "https://i.imgur.com/Av0I6kd.mp4",
      "https://i.imgur.com/IT68gkr.mp4",
      "https://i.imgur.com/QNsVlAz.mp4",
      "https://i.imgur.com/mdyhVSR.mp4",
      "https://i.imgur.com/D2rSL80.mp4",
      "https://i.imgur.com/JjI5x0o.mp4",
      "https://i.imgur.com/siRLWDm.mp4",
      "https://i.imgur.com/2vxb7qq.mp4",
      "https://i.imgur.com/zFfqqFh.mp4",
      "https://i.imgur.com/PSF642A.mp4",
      "https://i.imgur.com/TWw2O8K.mp4",
      "https://i.imgur.com/wscK2NB.mp4",
      "https://i.imgur.com/dU00I8t.mp4",
      "https://i.imgur.com/mw2KglD.mp4",
      "https://i.imgur.com/RXYMEwu.mp4"
],
"NOBITA-VIDEO": [
      "https://i.imgur.com/u5N7sqe.mp4",
      "https://i.imgur.com/0u32UXX.mp4",
      "https://i.imgur.com/sj3Asr2.mp4",
      "https://i.imgur.com/sJ3iQFR.mp4",
      "https://i.imgur.com/6IxQjHb.mp4",
      "https://i.imgur.com/SpQImVm.mp4",
      "https://i.imgur.com/rsXHTME.mp4",
      "https://i.imgur.com/bVCNwBl.mp4",
      "https://i.imgur.com/lpLN8j6.mp4",
      "https://i.imgur.com/mNekuge.mp4",
      "https://i.imgur.com/5EXQnUm.mp4",
      "https://i.imgur.com/sn1nM55.mp4",
      "https://i.imgur.com/vatwDvn.mp4",
      "https://i.imgur.com/Is914QQ.mp4",
      "https://i.imgur.com/4EGKkBr.mp4",
      "https://i.imgur.com/KMhExnR.mp4",
      "https://i.imgur.com/2exQMrj.mp4",
      "https://i.imgur.com/yjDclse.mp4",
      "https://i.imgur.com/2exQMrj.mp4",
      "https://i.imgur.com/yjDclse.mp4",
      "https://i.imgur.com/OxkI89B.mp4",
      "https://i.imgur.com/Ma5IKum.mp4",
      "https://i.imgur.com/TDx2wE5.mp4",
      "https://i.imgur.com/xgAoeB9.mp4",
      "https://i.imgur.com/TDx2wE5.mp4",
      "https://i.imgur.com/xgAoeB9.mp4",
      "https://i.imgur.com/vKtOrOC.mp4",
      "https://i.imgur.com/BfeZuuR.mp4",
      "https://i.imgur.com/8zvYfUL.mp4",
      "https://i.imgur.com/dUtiu6e.mp4",
      "https://i.imgur.com/brJkCMN.mp4",
      "https://i.imgur.com/A7jM45X.mp4",
      "https://i.imgur.com/g7DH0YU.mp4",
      "https://i.imgur.com/4aWS06D.mp4",
      "https://i.imgur.com/pHsTWyQ.mp4"
],
"NATURAL-VIDEO": [
      "https://i.imgur.com/s0enSFR.mp4",
      "https://i.imgur.com/G10APIS.mp4",
      "https://i.imgur.com/JCR8tC2.mp4",
      "https://i.imgur.com/nxYfqih.mp4",
      "https://i.imgur.com/eFVgw1Q.mp4",
      "https://i.imgur.com/TygOziE.mp4",
      "https://i.imgur.com/7XWsucf.mp4",
      "https://i.imgur.com/Joil59R.mp4",
      "https://i.imgur.com/ZtX1PXj.mp4",
      "https://i.imgur.com/Sxmc9vr.mp4",
      "https://i.imgur.com/DoH02UH.mp4",
      "https://i.imgur.com/1YPakcd.mp4",
      "https://i.imgur.com/Hj4ifk4.mp4",
      "https://i.imgur.com/pnzQX3o.mp4",
      "https://i.imgur.com/DKKCNTN.mp4",
      "https://i.imgur.com/THNxq4W.mp4",
      "https://i.imgur.com/68C43RD.mp4",
      "https://i.imgur.com/eM9oxrU.mp4",
      "https://i.imgur.com/fyzuKIb.mp4",
      "https://i.imgur.com/miliKnM.mp4",
      "https://i.imgur.com/eKdcfcV.mp4",
      "https://i.imgur.com/rrhSt3d.mp4",
      "https://i.imgur.com/BAADKLG.mp4",
      "https://i.imgur.com/YNXeRgF.mp4",
      "https://i.imgur.com/qkWLIcB.mp4",
      "https://i.imgur.com/LxgMw4v.mp4",
      "https://i.imgur.com/gFikegj.mp4",
      "https://i.imgur.com/joGj9PK.mp4",
      "https://i.imgur.com/M2IAXUW.mp4",
      "https://i.imgur.com/BZmbdqq.mp4",
      "https://i.imgur.com/7zGi8qk.mp4",
      "https://i.imgur.com/Bxxxhx7.mp4",
      "https://i.imgur.com/y48JOJ4.mp4",
      "https://i.imgur.com/9Tp7DLu.mp4"
],
"NATOK-VIDEO": [
      "https://i.imgur.com/iNCRwUz.mp4",
      "https://i.imgur.com/Opeg9MG.mp4",
      "https://i.imgur.com/6nvzJ1q.mp4",
      "https://i.imgur.com/7dqTUvv.mp4",
      "https://i.imgur.com/eCF9cBd.mp4",
      "https://i.imgur.com/iutOxsG.mp4",
      "https://i.imgur.com/G6HsY3Z.mp4",
      "https://i.imgur.com/9xiSW5o.mp4",
      "https://i.imgur.com/NT3LT2w.mp4",
      "https://i.imgur.com/vywuYQ8.mp4",
      "https://i.imgur.com/iyNLH0u.mp4",
      "https://i.imgur.com/GbOiBxK.mp4",
      "https://i.imgur.com/tuaCyjp.mp4",
      "https://i.imgur.com/TQIejDd.mp4",
      "https://i.imgur.com/DmC9av3.mp4",
      "https://i.imgur.com/Ev3TJKG.mp4",
      "https://i.imgur.com/XItdI9A.mp4",
      "https://i.imgur.com/m7zvwaq.mp4",
      "https://i.imgur.com/i3VQpLm.mp4",
      "https://i.imgur.com/C9ap29j.mp4",
      "https://i.imgur.com/GFY5fvj.mp4",
      "https://i.imgur.com/VwDPT3u.mp4",
      "https://i.imgur.com/qEfCFwj.mp4",
      "https://i.imgur.com/u8RVSk4.mp4",
      "https://i.imgur.com/G8uYNxl.mp4",
      "https://i.imgur.com/wXIBgQg.mp4",
      "https://i.imgur.com/rDNtrkr.mp4",
      "https://i.imgur.com/HmHXjyJ.mp4",
      "https://i.imgur.com/SoVP1Qe.mp4",
      "https://i.imgur.com/vznF0YY.mp4",
      "https://i.imgur.com/J59Hl1t.mp4",
      "https://i.imgur.com/dshmNdc.mp4",
      "https://i.imgur.com/cy4w6Tz.mp4",
      "https://i.imgur.com/0785PGJ.mp4",
      "https://i.imgur.com/OS2lRVW.mp4",
      "https://i.imgur.com/qh295t5.mp4",
      "https://i.imgur.com/c98dIlK.mp4",
      "https://i.imgur.com/J524CfA.mp4",
      "https://i.imgur.com/DEBRSER.mp4",
      "https://i.imgur.com/xgpGdNe.mp4",
      "https://i.imgur.com/mHa55LQ.mp4",
      "https://i.imgur.com/wK9pmGn.mp4",
      "https://i.imgur.com/BeiUY8F.mp4",
      "https://i.imgur.com/6YH1wQL.mp4",
      "https://i.imgur.com/A2OAuU9.mp4",
      "https://i.imgur.com/v8IXycg.mp4",
      "https://i.imgur.com/mlII2Ds.mp4",
      "https://i.imgur.com/Jf5ZmWU.mp4",
      "https://i.imgur.com/BsiB9jf.mp4",
      "https://i.imgur.com/QCNaneS.mp4",
      "https://i.imgur.com/1tBRKcN.mp4",
      "https://i.imgur.com/rbPxmy8.mp4",
      "https://i.imgur.com/IldLvnw.mp4",
      "https://i.imgur.com/iXrSTuY.mp4",
      "https://i.imgur.com/3H2chHj.mp4"
],
"MIX-FULL-VIDEO": [
      "https://i.imgur.com/yItovMb.mp4",
      "https://i.imgur.com/OaU2e69.mp4",
      "https://i.imgur.com/UZAAzcx.mp4",
      "https://i.imgur.com/RPUyukS.mp4",
      "https://i.imgur.com/8Np97fx.mp4",
      "https://i.imgur.com/KsLP1DM.mp4",
      "https://i.imgur.com/yeDzTXm.mp4",
      "https://i.imgur.com/iKpYdsR.mp4",
      "https://i.imgur.com/hFmXqnA.mp4",
      "https://i.imgur.com/ceLi4UY.mp4",
      "https://i.imgur.com/illcVXw.mp4",
      "https://i.imgur.com/Nr0OI0j.mp4",
      "https://i.imgur.com/korHFQ4.mp4",
      "https://i.imgur.com/b1I4PHo.mp4",
      "https://i.imgur.com/u5JiQIH.mp4",
      "https://i.imgur.com/P5yeu7C.mp4",
      "https://i.imgur.com/fyO0lLh.mp4",
      "https://i.imgur.com/IL1Ep9Y.mp4",
      "https://i.imgur.com/1GgxoG9.mp4",
      "https://i.imgur.com/s5DniRf.mp4",
      "https://i.imgur.com/SDl4ZWM.mp4",
      "https://i.imgur.com/X8Eu27M.mp4",
      "https://i.imgur.com/Ny4b8iv.mp4",
      "https://i.imgur.com/9BVC3PH.mp4",
      "https://i.imgur.com/ct4EPpQ.mp4",
      "https://i.imgur.com/pk7XM1Q.mp4",
      "https://i.imgur.com/yOvmlQ1.mp4",
      "https://i.imgur.com/qjhFfFQ.mp4",
      "https://i.imgur.com/hTDbS5N.mp4",
      "https://i.imgur.com/jE20FMj.mp4",
      "https://i.imgur.com/15Kse6h.mp4",
      "https://i.imgur.com/D5aipj7.mp4",
      "https://i.imgur.com/CZUpSsZ.mp4",
      "https://i.imgur.com/FdPnMTq.mp4",
      "https://i.imgur.com/W1kyb1s.mp4",
      "https://i.imgur.com/if7UhrC.mp4",
      "https://i.imgur.com/otf4nS6.mp4",
      "https://i.imgur.com/1TD3alE.mp4",
      "https://i.imgur.com/BGdd0x9.mp4",
      "https://i.imgur.com/MtWWuNZ.mp4",
      "https://i.imgur.com/mOebpTn.mp4",
      "https://i.imgur.com/OpSviui.mp4",
      "https://i.imgur.com/Hj7gMrL.mp4",
      "https://i.imgur.com/07pGexF.mp4",
      "https://i.imgur.com/BgPrwsL.mp4"
],
 "FREE-FIRE-VIDEO": [
      "https://i.imgur.com/sL6iIV5.mp4",
      "https://i.imgur.com/kS7SDdc.mp4",
      "https://i.imgur.com/x4Ia9wi.mp4",
      "https://i.imgur.com/aYUXixH.mp4",
      "https://i.imgur.com/l3zk86E.mp4",
      "https://i.imgur.com/gFYpBSn.mp4",
      "https://i.imgur.com/QZZPkeY.mp4",
      "https://i.imgur.com/LRSfvqD.mp4",
      "https://i.imgur.com/Cm3188l.mp4",
      "https://i.imgur.com/Cm3188l.mp4",
      "https://i.imgur.com/QG8DEb8.mp4",
      "https://i.imgur.com/2nhUpjN.mp4",
      "https://i.imgur.com/xWbQls8.mp4",
      "https://i.imgur.com/ZJGJdcL.mp4",
      "https://i.imgur.com/fC8gjAD.mp4",
      "https://i.imgur.com/lXZjWd6.mp4",
      "https://i.imgur.com/fC8gjAD.mp4",
      "https://i.imgur.com/1C3fQK1.mp4",
      "https://i.imgur.com/pcc3RL6.mp4",
      "https://i.imgur.com/9VK833x.mp4",
      "https://i.imgur.com/SPSCsoL.mp4",
      "https://i.imgur.com/4BpgEos.mp4",
      "https://i.imgur.com/EYXZR79.mp4",
      "https://i.imgur.com/NeYjAKg.mp4",
      "https://i.imgur.com/Rsktftp.mp4",
      "https://i.imgur.com/6nxJFwB.mp4",
      "https://i.imgur.com/WSM5MCj.mp4",
      "https://i.imgur.com/wWMxgrZ.mp4",
      "https://i.imgur.com/nSnBW3z.mp4",
      "https://i.imgur.com/xTaC2Bi.mp4",
      "https://i.imgur.com/3AKyhW5.mp4",
      "https://i.imgur.com/rYol0jl.mp4",
      "https://i.imgur.com/dDfghV8.mp4",
      "https://i.imgur.com/sOcNMuK.mp4",
      "https://i.imgur.com/iAe53o4.mp4",
      "https://i.imgur.com/cnNos7d.mp4",
      "https://i.imgur.com/HmEjrKT.mp4",
      "https://i.imgur.com/jiGqDvh.mp4",
      "https://i.imgur.com/VTcH66o.mp4",
      "https://i.imgur.com/B4kbNF7.mp4"
 ],
 "FOOTBALL-VIDEO": [
      "https://i.imgur.com/URn99v1.mp4",
      "https://i.imgur.com/J6qrjqP.mp4",
      "https://i.imgur.com/AEbXAJU.mp4",
      "https://i.imgur.com/XanuIJH.mp4",
      "https://i.imgur.com/KAiOpqY.mp4",
      "https://i.imgur.com/ar58O9i.mp4",
      "https://vt.tiktok.com/ZSMJXU8EC"
 ],
  "ITEM-VIDEO": [
      "https://i.imgur.com/G26ADLB.mp4",
      "https://i.imgur.com/SjmVLRO.mp4",
      "https://i.imgur.com/TmtN3Qp.mp4",
      "https://i.imgur.com/9NPlChB.mp4",
      "https://i.imgur.com/dUkVc3m.mp4",
      "https://i.imgur.com/dUkVc3m.mp4",
      "https://i.imgur.com/86iAcN5.mp4",
      "https://i.imgur.com/dCg9bGH.mp4",
      "https://i.imgur.com/pzQcUGE.mp4",
      "https://i.imgur.com/FMMxX7Y.mp4",
      "https://i.imgur.com/p8cZKZo.mp4",
      "https://i.imgur.com/4hmvU0G.mp4",
      "https://i.imgur.com/mYd02mH.mp4",
      "https://i.imgur.com/M3u1x25.mp4",
      "https://i.imgur.com/8oX8Cl0.mp4",
      "https://i.imgur.com/U5wsgmz.mp4",
      "https://i.imgur.com/vm6TUHz.mp4",
      "https://i.imgur.com/i2B7yy6.mp4",
      "https://i.imgur.com/KSIOtqC.mp4",
      "https://i.imgur.com/yCIDZqP.mp4",
      "https://i.imgur.com/nQTe46T.mp4",
      "https://i.imgur.com/Y3AB4Hx.mp4",
      "https://i.imgur.com/556UzNL.mp4",
      "https://i.imgur.com/CwBE5tk.mp4",
      "https://i.imgur.com/dbWBQ5W.mp4",
      "https://i.imgur.com/jUlfoTR.mp4",
      "https://i.imgur.com/jUlfoTR.mp4",
      "https://i.imgur.com/8zpVqJK.mp4",
      "https://i.imgur.com/eh9I6Rm.mp4",
      "https://i.imgur.com/VGs9xZQ.mp4",
      "https://i.imgur.com/SRmWhsV.mp4",
      "https://i.imgur.com/w7E3FpU.mp4",
      "https://i.imgur.com/LL8zj0j.mp4",
      "https://i.imgur.com/w2SfYTp.mp4",
      "https://i.imgur.com/vZeeWLo.mp4",
      "https://i.imgur.com/vNgefkB.mp4",
      "https://i.imgur.com/bXjpWsJ.mp4",
      "https://i.imgur.com/tA2P7q2.mp4",
      "https://i.imgur.com/LzXzTw9.mp4",
      "https://i.imgur.com/ENRgE4x.mp4",
      "https://i.imgur.com/CGCYDDq.mp4"
  ],
  "BABY-VIDEO": [
      "https://i.imgur.com/na2yELI.mp4",
      "https://i.imgur.com/WETgR7Y.mp4",
      "https://i.imgur.com/QM6cI1y.mp4",
      "https://i.imgur.com/FhlYV3Y.mp4",
      "https://i.imgur.com/dNldyDZ.mp4",
      "https://i.imgur.com/ptHuH2w.mp4",
      "https://i.imgur.com/2H8Fmkk.mp4",
      "https://i.imgur.com/R42nQEq.mp4",
      "https://i.imgur.com/JMkoAyA.mp4",
      "https://i.imgur.com/Hl1vq4D.mp4",
      "https://i.imgur.com/Flm78Ph.mp4",
      "https://i.imgur.com/PDnHuWv.mp4",
      "https://i.imgur.com/eiXiggG.mp4",
      "https://i.imgur.com/YxCt3gc.mp4",
      "https://i.imgur.com/3CXsP6i.mp4"
  ],
  "GIRL-VIDEO": [
      "https://i.imgur.com/o1PTdGV.mp4",
      "https://i.imgur.com/RKJwOpe.mp4",
      "https://i.imgur.com/yCSj2Kh.mp4",
      "https://i.imgur.com/nyzI1cK.mp4",
      "https://i.imgur.com/CbgckN1.mp4",
      "https://i.imgur.com/cDpqOCp.mp4",
      "https://i.imgur.com/TXUD5TM.mp4",
      "https://i.imgur.com/D6PyM90.mp4",
      "https://i.imgur.com/pLvL9dP.mp4",
      "https://i.imgur.com/RvLOsJZ.mp4",
      "https://i.imgur.com/kM5wgxs.mp4",
      "https://i.imgur.com/lRrlGWI.mp4",
      "https://i.imgur.com/mNFOR07.mp4",
      "https://i.imgur.com/tQjXy3a.mp4",
      "https://i.imgur.com/AezYExh.mp4",
      "https://i.imgur.com/N6kihzz.mp4",
      "https://i.imgur.com/fkRizD5.mp4",
      "https://i.imgur.com/IPOLLbu.mp4"
  ],
  "CATS-VIDEO": [
      "https://i.imgur.com/LzXzTw9.mp4",
      "https://i.imgur.com/s4Tfoql.mp4",
      "https://i.imgur.com/k3971qb.mp4",
      "https://i.imgur.com/ZsnYmvb.mp4",
      "https://i.imgur.com/BjXVxIq.mp4",
      "https://i.imgur.com/DkjMVwX.mp4",
      "https://i.imgur.com/bZXTYTO.mp4",
      "https://i.imgur.com/D7443So.mp4",
      "https://i.imgur.com/ekfNkRo.mp4"
  ],
  "LYRICS-VIDEO": [
      "https://i.imgur.com/Zdyxg7P.mp4",
      "https://i.imgur.com/AW7paTb.mp4",
      "https://i.imgur.com/4FGHD8d.mp4",
      "https://i.imgur.com/XmpNpYt.mp4",
      "https://i.imgur.com/sZ01LgJ.mp4",
      "https://i.imgur.com/0RVvTAN.mp4",
      "https://i.imgur.com/P0IUmiG.mp4",
      "https://i.imgur.com/12hQnsb.mp4",
      "https://i.imgur.com/IEDHf4P.mp4",
      "https://i.imgur.com/sMbBFWm.mp4",
      "https://i.imgur.com/wP5sOJW.mp4",
      "https://i.imgur.com/zg60azD.mp4",
      "https://i.imgur.com/zsKTADg.mp4",
      "https://i.imgur.com/NjJK9Np.mp4",
      "https://i.imgur.com/0ueXnpB.mp4"
  ],
  "LOFI-VIDEO": [
      "https://i.imgur.com/g6cdosz.mp4",
      "https://i.imgur.com/4gY1bWL.mp4",
      "https://i.imgur.com/Y2AnTbO.mp4",
      "https://i.imgur.com/slARoKZ.mp4",
      "https://i.imgur.com/HU45akB.mp4"
  ],
  "FUNNY-VIDEO": [
      "https://i.imgur.com/evswpXP.mp4",
      "https://i.imgur.com/CbwvstK.mp4",
      "https://i.imgur.com/19j5Vhh.mp4",
      "https://i.imgur.com/VYRYUNJ.mp4",
      "https://i.imgur.com/w2DN7Vr.mp4",
      "https://i.imgur.com/CiAuZc7.mp4",
      "https://i.imgur.com/JK5LZnq.mp4",
      "https://i.imgur.com/cH5mhfJ.mp4",
      "https://i.imgur.com/WmDqN6m.mp4",
      "https://i.imgur.com/e2OjqeQ.mp4",
      "https://i.imgur.com/FmOKl2S.mp4",
      "https://i.imgur.com/vrQpE9G.mp4",
      "https://i.imgur.com/H8fHZdu.mp4",
      "https://i.imgur.com/G5i0xcY.mp4",
      "https://i.imgur.com/lqPyKgZ.mp4",
      "https://i.imgur.com/sUJFShv.mp4",
      "https://i.imgur.com/WzXz13s.mp4"
  ],
};
const PAGE_SIZE = 11;

module.exports = {
  config: {
    name: "album",
        aliases: [],
        version: "1.5.0",
        author: "SK-SIDDIK-KHAN",
        countDown: 5,
        role: 0,
        usePrefix: true,
    description: {
            en: "Command description"
        },
        category: "user",
        guide: {
            en: "{pn}"
        }
},
    langs: {
        en: { syntaxError: "Please use the correct syntax: {pn}!" }
    },
  onStart: async function ({ api, event, message, args }) {
    const categoryKeys = Object.keys(categories);
    let page = 1;
    if (args.length > 0) {
      const inputPage = parseInt(args[0], 10);
      if (!isNaN(inputPage) && inputPage > 0) {
        page = inputPage;
      }
    }
    const totalPages = Math.ceil(categoryKeys.length / PAGE_SIZE);
    if (page > totalPages) {
      return message.reply(`❌ Page ${page} doesn't exist. Total pages: ${totalPages}`);
    }
    const startIndex = (page - 1) * PAGE_SIZE;
    const endIndex = startIndex + PAGE_SIZE;
    const currentPageCategories = categoryKeys.slice(startIndex, endIndex);
    let msg =
      `╭╼|━♡𝐒𝐈𝐃𝐃𝐈𝐊-𝐁𝐎𝐓-𝟎𝟕♡━|╾╮\n\n` +
      `আপনার পছন্দের ভিডিও দেখতে একটি নাম্বারে রিপ্লাই করুন:\n\n` +
      `╰╼|━♡𝐒𝐈𝐃𝐃𝐈𝐊-𝐁𝐎𝐓-𝟎𝟕♡━|╾╯\n` +
      `┏━━━━━━━━━━━━━━━━━┓\n` +
      currentPageCategories
        .map((cat, i) => `┣➤ ${startIndex + i + 1}. ${cat.toUpperCase()}`)
        .join("\n") +
      `\n┗━━━━[𝗦𝗜𝗗𝗗𝗜𝗞-𝗕𝗢𝗧]━━━━┛\n` +
      `\n☽━━━━━━━━━━━━━━━━━━☾\n           🔰 | 𝐏𝐚𝐠𝐞 [ ${page} / ${totalPages} ] 🔰\n☽━━━━━━━━━━━━━━━━━━☾`;
    message.reply({ body: msg }, (err, replyMsg) => {
      if (err) return;
      global.GoatBot.onReply.set(replyMsg.messageID, {
        commandName: "album",
        messageID: replyMsg.messageID,
        author: event.senderID,
        type: "selectCategory",
      });
      setTimeout(() => {
        api.unsendMessage(replyMsg.messageID).catch(() => {});
      }, 30000);
    });
  },
  onReply: async function ({ message, event, Reply }) {
    if (Reply.author !== event.senderID) {
      return message.reply("⚠️ You are not authorized to reply to this option");
    }
    const categoryKeys = Object.keys(categories);
    const num = parseInt(event.body.trim());
    if (isNaN(num) || num < 1 || num > categoryKeys.length) {
      return message.reply("❌ Invalid input. Please enter a valid number");
    }
    const category = categoryKeys[num - 1];
    const videoURL = categories[category][Math.floor(Math.random() * categories[category].length)];
    const fileName = path.basename(videoURL);
    const filePath = path.join(__dirname, "cache", "album", fileName);
    if (!fs.existsSync(path.dirname(filePath))) {
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
    }
    const loadingMsg = await message.reply(`⏳ Loading ${category.toUpperCase()}`);
    try {
      if (!fs.existsSync(filePath)) {
        await downloadFile(filePath, videoURL);
      }
      await message.reply({
        body: `✅ Here's Your ${category.toUpperCase()}`,
        attachment: fs.createReadStream(filePath),
      });
      message.unsend(loadingMsg.messageID);
    } catch (err) {
      console.error(err);
      message.reply("❌ Failed to load video");
    }
  },
};

function downloadFile(filePath, url) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(filePath);
    https
      .get(url, (res) => {
        res.pipe(file);
        file.on("finish", () => file.close(resolve));
      })
      .on("error", (err) => {
        fs.unlink(filePath, () => {});
        reject(err);
      });
  });
}
